name: AUnit Tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v2

    - name: Setup
      run: |
        cd ..
        git clone https://github.com/bxparks/AUnit
        git clone https://github.com/bxparks/AceCommon
        git clone https://github.com/bxparks/AceCRC
        git clone https://github.com/bxparks/AceUtils
        git clone https://github.com/bxparks/AceRoutine

    - name: Verify examples
      run: |
        make -C examples
        make -C libraries

    - name: Verify tests
      run: |
        # tests/IPAddressTest requires EPOXY_CORE_ESP8266, which requires clean
        make -C tests clean
        make -C tests tests
        make -C tests runtests
        # clean after tests/IPAddressTest to revert to EPOXY_CORE_AVR
        make -C libraries clean
        make -C libraries tests
        make -C libraries runtests
